# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoCall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoCall
  pod 'SnapKit'
  pod 'libksygpulive/libksygpulive'

  target 'VideoCallTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
